import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { NextIntlClientProvider } from 'next-intl';
import "./globals.css";

import { notFound } from 'next/navigation'
import { unstable_setRequestLocale, getMessages } from 'next-intl/server';
import { locales, defaultLocale, getLocale, clerkLocalizations, Locale } from '@/configs/localeConfig';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map(locale => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params: { locale }
}: {
  children: ReactNode
  params: { locale: string }
}) {
  const validLocale: Locale = getLocale(locale);
  unstable_setRequestLocale(validLocale);

  let messages;
  try {
    messages = await getMessages();
  } catch (error) {
    notFound()
  }
  return (
    <html lang={locale}>
    <body>
      <NextIntlClientProvider locale={locale} messages={messages}>
        {children}
      </NextIntlClientProvider>
    </body>
  </html>
  );
}
